### ISSUE TITLE
Tournaments and teams

### ISSUE THREAD

**Issue by silverforest** [MetalMichael/LAN-Website#3]
Hi, thanks a bunch for that quick update on the last issue, worked wonders.

I'm here to bring you some new bugs.

When creating a new tournament og tournament team I get these errors when I afterwards go to check them in the tournament list and team list:

Fatal error: Uncaught exception 'Exception' with message 'Class not found: 'Memcached"' in /home/4/h/helgelan/www/lib/LanWebsite/Autoload.php:6 Stack trace: #0 /home/4/h/helgelan/www/lib/LanWebsite/Cache.php(10): __autoload('Memcached') #1 /home/4/h/helgelan/www/lib/LanWebsite/Cache.php(26): LanWebsite_Cache::init() #2 /home/4/h/helgelan/www/lib/Tournament/Team.php(15): LanWebsite_Cache::get('tournament', 'team_14', NULL) #3 /home/4/h/helgelan/www/lib/Tournament/Main.php(62): Tournament_Team->__construct('14') #4 /home/4/h/helgelan/www/public/controllers/teams.php(46): Tournament_Main::team('14') #5 [internal function]: Teams_Controller->get_Self(Array) #6 /home/4/h/helgelan/www/lib/LanWebsite/Controller.php(94): call_user_func(Array, Array) #7 /home/4/h/helgelan/www/lib/LanWebsite/Main.php(85): LanWebsite_Controller->handleRequest() #8 /home/4/h/helgelan/www/index.php(23): LanWebsite_Main::route(Array, 'home') #9 {main} thrown in /home/4/h/helgelan/www/lib/LanWebsite/Autoload.php on line 6

for tournament team (you also get a blank page with "Invalid Team ID" when creating one, it does fill in the database though)

Fatal error: Uncaught exception 'Exception' with message 'Class not found: 'Memcached"' in /home/4/h/helgelan/www/lib/LanWebsite/Autoload.php:6 Stack trace: #0 /home/4/h/helgelan/www/lib/LanWebsite/Cache.php(10): __autoload('Memcached') #1 /home/4/h/helgelan/www/lib/LanWebsite/Cache.php(20): LanWebsite_Cache::init() #2 /home/4/h/helgelan/www/lib/Tournament/Tournament.php(30): LanWebsite_Cache::set('tournament', 'tournament_13', Array) #3 /home/4/h/helgelan/www/lib/Tournament/Main.php(56): Tournament_Tournament->__construct('13', false) #4 /home/4/h/helgelan/www/public/controllers/tournaments.php(30): Tournament_Main::tournament('13') #5 [internal function]: Tournaments_Controller->get_Index(Array) #6 /home/4/h/helgelan/www/lib/LanWebsite/Controller.php(94): call_user_func(Array, Array) #7 /home/4/h/helgelan/www/lib/LanWebsite/Main.php(85): LanWebsite_Controller->handleRequest() #8 /home/4/h/helgelan/www/index.php(23): LanWebsite_Main::route(Array, 'home') #9 {main} thrown in /home/4/h/helgelan/www/lib/LanWebsite/Autoload.php on line 6

for tournament.

Biggest errorblocks I've ever seen, but it's probably a cinch for you guys

I also recommend having a locale option in settings so people don't need to change it directly in the index.php/admin.php files, as this controls the currency on the ticket page.

And lastly the register page doesn't stop people from registering over and over again with the exact same information, and it still gives a error on registering.

Hope to hear from you soon :)

**Comment by MetalMichael** [comment]
Ah, most of these look to be because Memcached isn't installed on my server. Or whatever server you've been testing on. I'll work in a way config for enabling/disabling cache.

Really, cache probably isn't needed when traffic is only going to be around 50 people. I was just in a habit of always using cache when I wrote it last summer, coming from a site with 20,000 users or something. Not that it does any harm, and it should still lower server load a small amount.

**Comment by silverforest** [comment]
Oh, I'm using it directly on a webhotel, I'll ask the hosting company to install memcached anyway.

**Comment by silverforest** [comment]
I removed memcached from cache.php so the errors are gone and now I can see the lists. But here's the next problem.

Now I'm not completely sure the system sets up matches for tournaments automatically, but when starting a tournament, admin -> tournament -> matches (and tournament -> standings) comes up empty and so does the "tournament_matches" table in the database. I'm not getting any errors, except it doesn't refresh the site or take me to the tournament when I click "start tournament", I have to refresh the site manually.

Am I missing something here?

Sorry for bothering you so much.
